{
 "title": "Dashboard Machine",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Nombre de CPU",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "machine_cpu_cores", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Nombre de CPU physiques",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "machine_cpu_physical_cores", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Mémoire disponible",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "machine_memory_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Mémoire utilisée pour les containers",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{image!=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{mode=\"idle\"}[1h])) ) * 100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}