{
 "title": "Dashboard Principal",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Usage RAM par conteneur",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (name)(container_memory_usage_bytes{image!=\"\",container_label_org_label_schema_group=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Usage de la RAM (en MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes) / 1024 / 1024",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(container_memory_working_set_bytes) / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Utilisation du CPU en % (par conteneur)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=\"apirecepteur\"}[1h])) by (name) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=\"streamenvoi\"}[1h])) by (name) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=\"dashboard\"}[1h])) by (name) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=\"prometheus\"}[1h])) by (name) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=\"grafana\"}[1h])) by (name) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=\"cadvisor\"}[1h])) by (name) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=\"redis-service\"}[1h])) by (name) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=\"worker-bigquery\"}[1h])) by (name) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime (disponibilité des conteneurs)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(time() - container_start_time_seconds{name=~\".+\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Trafic réseau",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{name=\"apirecepteur\"}[5m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total{name=\"streamenvoi\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}