{
 "title": "Dashboard RAM total",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Usage total de la RAM (en MB)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{image!=\"\",container_label_org_label_schema_group=\"\"}) by (name) / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM \"Réelle\" (en MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\",container_label_org_label_schema_group=\"\"}) by (name) / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Utilisation du cache (en MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "(sum(container_memory_usage_bytes{image!=\"\",container_label_org_label_schema_group=\"\"}) by (name) - sum(container_memory_working_set_bytes{image!=\"\",container_label_org_label_schema_group=\"\"}) by (name)) / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}